---
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r test-requirements.txt
script:
  - py.test --cov=./crypt_roll ./tests/tests.py
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
